vmware/powershell-module-for-vmware-cloud-foundation-certificate-management

VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1

- Added parameter descriptions to be used for upcoming documentation.
- Trimmed trailing whitespace, where applicable.
- Adjusted spacing, where applicable.
- Updated module version from v1.0.0.1001 to v1.0.0.1002.

chore: add parameter descriptions

---

VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1

- Added missing `.SYNOPSIS`, where applicable.
- Updated formatting for pending documentation.
- Updated module version from v1.0.0.1002 to v1.0.0.1003.

chore: update cmdlet details

---

README.md

We are only supporting VCF 4.5.0 as this module has been validated with 4.5.0 only at this time. Future release will support newer VCF versions as well.  

docs: uodate README.md

---

docs/index.md

Updated PowerShell Gallery URL.

docs: update psgallery link

---

docs/documentation/user-guide/esxi-certificate-management.md
docs/snippets/vars-esxi-cer-mode.ps1
docs/snippets/vars-linux.ps1

There were a few minor changes needed to the generated github docs. This request addresses those. It is just updates to doc related files. No code changes. 

docs: fix cmdlet parameters

---

CHANGELOG.md
README.md
VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1
docs/documentation/functions/Confirm-ESXiCertificateInstalled.md
docs/documentation/functions/Get-ESXiLockdownMode.md
docs/documentation/functions/Restart-ESXiHost.md
docs/documentation/functions/Set-ESXiLockdownMode.md
docs/documentation/functions/Test-EsxiCertMgmtChecks.md
docs/documentation/user-guide/esxi-certificate-management.md
docs/index.md
mkdocs.yml

- Add support for PowerShell Core and VMware PhotonOS.
- Add support for a ESXi certificate management pre-check.
- Enhanced `Get-vSANHealthSummary` by improving log messages and adding checks for vSAN services.
- Updated the case for functions from `ESXi...` to `Esxi`.
Closes #27 
Closes #30

feat: add support for Powershell Core, PhotonOS and pre-check

---

.github/workflows/ci-module.yml
.github/workflows/deploy.yml
.github/workflows/issues.yml
.github/workflows/lock-threads.yml
.github/workflows/pull-requests.yml
.github/workflows/stale.yml

Pin actions to a full length commit SHA.
Ref: [Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
Please describe: `chore`

chore(gha): pin actions to commit sha

---

VMware.CloudFoundation.CertificateManagement.psm1
docs/documentation/functions/Confirm-CAInvCenterServer.md
docs/documentation/functions/Confirm-EsxiCertificateInstalled.md
docs/documentation/functions/Get-EsxiCertificateMode.md
docs/documentation/functions/Get-EsxiCertificateThumbprint.md
docs/documentation/functions/Get-EsxiLockdownMode.md
docs/documentation/functions/Get-vCenterCertificateThumbprint.md
docs/documentation/functions/Get-vSANHealthSummary.md
docs/documentation/functions/Install-EsxiCertificate.md
docs/documentation/functions/Request-EsxiCsr.md
docs/documentation/functions/Restart-EsxiHost.md
docs/documentation/functions/Set-EsxiCertificateMode.md
docs/documentation/functions/Set-EsxiLockdownMode.md
docs/documentation/functions/Test-EsxiCertMgmtChecks.md
docs/requirements.txt
mkdocs.yml

- Updated headers, readability, and order of the docs.
- Updated parameter description to match other module docs.
- Adds `mkdocs-open-in-new-tab` to open external links in a new tab.
- Changes `Documentation` to `Reference` to help align with other modules. The whole site is "documentation".
- Renamed `.md` files for four docs not appearing due to being case sensitive (`git mv -f <old-name> <new-name>`), correcting the below error:
```bash
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
- documentation/functions/Confirm-ESXiCertificateInstalled.md
- documentation/functions/Get-ESXiLockdownMode.md
- documentation/functions/Restart-ESXiHost.md
- documentation/functions/Set-ESXiLockdownMode.md
WARNING  -  A relative path to …
```

docs: fix-up docs

---

docs/index.md

Added a note that ESXi certificate management for VMware Cloud Foundation on Dell EMC VxRail is not supported.

docs: add vxrail note

---

README.md
VMware.CloudFoundation.CertificateManagement.psm1
docs/index.md

Updated documentation to reflect support for new capabilities. 
`index.md` and `readme.md` have been updated with details about additional module capability

docs: update module support

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1
docs/documentation/functions/Request-VCFSignedCertificate.md
docs/documentation/functions/Set-VCFCertificateAuthority.md
docs/documentation/user-guide/esxi-certificate-management.md
docs/documentation/user-guide/vcf-certificate-management.md
mkdocs.yml

- **Breaking Change**: Renamed `Set-SddcCertificateAuthority` to `Set-VCFCertificateAuthority`
- **Breaking Change**: Renamed `Request-SddcCertificate` to `Request-VCFSignedCertificate` 
- Updated docs as per above changes. 
Closes #73

chore: update cmdlet names

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1

- Updated `Get-vSANHealthSummary` to report correct status
Closes #77

fix: update `Get-vSANHealthSummary` to report correct status

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1

Added support for use of secure strings for sensitive parameters.
Closes #88

feat: add secure strings for sensitive parameters

---

docs/community/index.md
docs/index.md
docs/requirements.txt
docs/snippets/install-module.ps1
docs/snippets/save-module-local-linux.ps1
docs/snippets/save-module-local-windows.ps1
mkdocs.yml

- Updates installation documentation for the v1.6.0 release.
- Updates the MkDocs plugin requirements.

docs: documentation updates

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
docs/index.md
docs/install.md

**Breaking Change**
Updates the module to support PowerShell 7.2 and later.

chore(deps): support pwsh 7.2 and later

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
VMware.CloudFoundation.CertificateManagement.psm1
docs/documentation/functions/Get-EsxiHostVsanMaintenanceModePrecheck.md
docs/documentation/functions/Install-VCFCertificate.md

- Updated `Install-EsxiCertificate` to include the `vsanDataMigrationMode` parameter. The ESXi host will enter maintenance mode with Migrate Power off VMs option disabled and vSAN data migration ,ode set to `EnsureAccessibility`.
- Add `Get-EsxiHostVsanMaintenanceModePrecheck` function to check for any issue with ESXi host entering a particular vSAN maintenance mode.
Closes #32 
Closes #100

feat: add migration mode option to `Install-EsxiCertificate`

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1

chore: set next release

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
docs/index.md
docs/snippets/install-module.ps1

Bumps PowerVCF from 2.4.0 to 2.4.1.

chore(deps): bump powervcf from 2.4.0 to 2.4.1

---

CHANGELOG.md

chore: release v1.5.1

---

CHANGELOG.md
VMware.CloudFoundation.CertificateManagement.psd1
tests/cert.tests.ps1
tests/inputData.json.example

Adds Pester testcases.
Closes #117

feat: add pester testcases

---

VMware.CloudFoundation.CertificateManagement.psm1
docs/documentation/functions/Install-VCFCertificate.md

Updates description for `Install-VCFCertificates`.

docs: update description for Install-VCFCertificates

---

VMware.CloudFoundation.CertificateManagement.psm1
docs/snippets/install-module.ps1

fix a bug when importing module.  a missing } fixed a double "else" in the if/else statement as well as the missing } when importing module.

fix: fix a bug when import module

---

CHANGELOG.md

Release v1.5.5.
Release v1.5.5.

chore(release): v1.5.5
